version: '3'

services:

  mysql-development:
    image: mysql:5.7
    environment:
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - 3306:3306
    expose:
      - 3306